name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:      
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker build --target test . --file Dockerfile 
    - name: Build the Docker image
      run: docker build --target build . --file Dockerfile --tag ip-echo:$(date +%s)
    - name: Run
      run: docker build --target run . --file Dockerfile 
